incorporate changes from production code

diff --git a/boj b/boj
--- a/boj
+++ b/boj
@@ -2,7 +2,7 @@
 
 metadata() {
     cat <<EOS
-    @@VERSION 0.6.3
+    @@VERSION 0.6.5
     @@AUTHOR Paul Hoffman <paul@flo.org>
     @@COPYRIGHT Copyright 2012 Fenway Libraries Online.
 EOS
@@ -20,14 +20,17 @@ typeset HOST=$(print -P %M)
 typeset mailfrom=${MAILFROM:-$user} mailto=${MAILTO:-$user} mailsubj=${MAILSUBJ:-'$H: [$r] $c'}
 typeset timestamp='%D{%Y%m%dT%H%M%S}'
 
-typeset begin="$(print -P $timestamp)"
+typeset begin="$(print -P $timestamp)" end
 typeset result
-integer err=0
 typeset cmdline cmd
 
 [[ -w $log || -w $log:h ]] || log=~/.bojlog
 
 main() {
+    if (( $# == 1 )) && [[ $1 == @* && -n $BOJ_ROOT && -x $BOJ_ROOT/${1[2,-1]}/run ]]; then
+        # boj @foo --> boj $BOJ_ROOT/foo
+        set -- -p ${BOJ_ROOT}/${1[2,-1]}
+    fi
     typeset opt
     while getopts :nmkreLd:g:o:l:f:t:s:p:v opt; do
         case $opt in
@@ -53,7 +56,16 @@ main() {
 
     # More setup
     if [[ -n $projdir ]]; then
-        cd $projdir
+        cd $projdir || exit 2
+        out=./out
+        log=./boj.log
+        msg=./msg
+        guard=./norun
+        [[ ! -e keepout    ]] || keepout=true
+        [[ ! -e alwaysmail ]] || alwaysmail=true
+        [[ ! -e nomail     ]] || nomail=true
+        [[ ! -e showenv    ]] || showenv=true
+        # Figure out the command to execute, and what args to give it
         if (( $# == 0 )); then
             # boj -p DIR
             cmd=./run
@@ -76,14 +88,6 @@ main() {
             cmd=./run
             cmdline="$projdir/run $*"
         fi
-        out=./out
-        log=./boj.log
-        msg=./msg
-        guard=./norun
-        [[ ! -e keepout    ]] || keepout=true
-        [[ ! -e alwaysmail ]] || alwaysmail=true
-        [[ ! -e nomail     ]] || nomail=true
-        [[ ! -e showenv    ]] || showenv=true
     else
         (( $#argv > 0 )) || usage
         cd $dir
@@ -91,44 +95,51 @@ main() {
         cmd=$1; shift
     fi
 
+    #  If something fails, we exit -- after calling our exit handler, which
+    #  takes care of logging and notification.
+    set -e
+    trap finish EXIT
+
     # Make sure all output goes to the designated file
     exec > $out 2>&1
 
-    # Set our exit handler, which takes care of logging and notification
-    TRAPEXIT() {
-        err=$?
-        set +e  # Turn off automatic exit on error
-        typeset end="$(print -P $timestamp)"
-        if [[ -z $result ]]; then
-            (( err != 0 )) || result=OK
-        fi
-        printf '%-4.4s %s %s %s\n' $result $begin $end $cmdline >> $log
-        # Send notification
-        typeset notify=false
-        if (( err != 0 )) || $alwaysmail; then
-            notify=true
-        elif [[ -s $out ]] && ! $nomail; then
-            notify=true
-        fi
-        ! $notify || send-notification
-        $keepout || rm -f $out
-    }
-
-    # Automatically exit if a command fails
-    set -e
-
-    # Make sure we got a command to execute
-    [[ -n $cmd ]] || usage
-
     # Run it (unless the guard file exists)
+    integer err
     if [[ -n $guard && -e $guard ]]; then
         result=SKIP
+        err=0
     else
-        result=FAIL
         $cmd $@
+        err=$?
     fi
 
-    # Everything else happens in TRAPEXIT
+    # Everything else happens in finish
+    trap - EXIT
+    finish $err
+}
+
+finish() {
+    integer err=${1:-$?}
+    set +e  # Turn off automatic exit on error
+    # print FINISH err=$err > /dev/tty
+    end="$(print -P $timestamp)"
+    if [[ -z $result ]]; then
+        if (( err == 0 )); then
+            result=OK
+        else
+            result=FAIL
+        fi
+    fi
+    printf '%-4.4s %s %s %s\n' $result $begin $end $cmdline >> $log
+    # Send notification
+    typeset notify=false
+    if (( err != 0 )) || $alwaysmail; then
+        notify=true
+    elif [[ -s $out ]] && ! $nomail; then
+        notify=true
+    fi
+    ! $notify || send-notification
+    $keepout || rm -f $out
 }
 
 usage() {
@@ -200,7 +211,14 @@ expand-escapes() {
         -e "s#\\\$4r#$(printf '%-4.4s' $result)#"           \
         -e "s#\\\$j#${projdir:t}#" -e "s#\\\$J#${projdir}#" \
         -e "s#\\\$u#${user}#"      -e "s#\\\$h#${host}#"    \
+        -e "s#\\\$b#${begin}#"     -e "s#\\\$e#${end}#"     \
+        -e "s#\\\$%#$(random)#"                             \
         -e "s#\\\$H#${HOST}#"      -e "s#\\\$c#${cmdline}#"
+}
+
+random() {
+    dd if=/dev/random count=1 2> /dev/null | openssl base64 | tr +/ XQ | read -r
+    print ${REPLY[1,16]}
 }
 
 main "$@"
